class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  # Oracle IDENTITY columns: ActiveRecord initializes id as 0.0 (not nil),
  # which bypasses GENERATED BY DEFAULT ON NULL. Reset to nil so Oracle generates.
  before_create :reset_zero_id

  # Oracle IDENTITY returns BigDecimal (e.g. 306.0) which produces
  # URLs like /categories/306.0/edit — Rails misinterprets ".0" as format.
  def to_param
    id&.to_i&.to_s
  end

  private

  def reset_zero_id
    self.id = nil if id == 0 || id == 0.0
  end
end
